apiVersion: demo.example.com/v1alpha1
kind: Sandbox
metadata:
  labels:
    app.kubernetes.io/name: mini-sandbox-controller
    app.kubernetes.io/managed-by: kustomize
  name: sandbox-sample
spec:
  # TODO(user): Add fields here
  image: nginx
